var data = [
    {
        id : 1,
        name : "Nước hoa  1",
        img : "NH-1.jpg",
        price: "200",
        best : true,
        nh : true,
        dh: false,
        dch: false,
        voucher:"",
    },
    {
        id : 2,
        name : "Nước hoa  2",
        img : "NH-2.jpg",
        price: "300",
        nh : true,
        best : true,
        dh: false,
        dch: false,
        voucher:"",
    },
    {
        id : 3,
        name : "Nước hoa  3",
        img : "NH-3.jpg",
        price: "400",
        nh : true,
        best : true,
        dh: false,
        dch: false,
        voucher:"" ,
    },
    {
        id : 4,
        name : "Nước hoa  4",
        img : "NH-1.jpg",
        price: "200",
        nh : true,
        best : true,
        dh: false,
        dch: false,
        voucher:"",
    },
    {
        id : 5,
        name : "Nước hoa  5",
        img : "NH-5.jpg",
        price: "200",
        nh : true,
        dh: false,
        dch: false,
        voucher:"",
    },
    {
        id : 6,
        name : "Nước hoa  6",
        img : "NH-6.jpg",
        price: "200",
        nh : true,
        dh: false,
        dch: false,
        voucher:"",
    },
    {
        id : 7,
        name : "Nước hoa  7",
        img : "NH-7.jpg",
        price: "200",
        nh : true,
        dh: false,
        dch: false,
        voucher:"",
    },
    {
        id : 8,
        name : "Nước hoa  8",
        img : "NH-8.jpg",
        price: "200",
        nh : true,
        dh: false,
        dch: false,
        voucher:"",
    },
    {
        id : 9,
        name : "Đồng hồ  1",
        img : "ĐH-1.jpg",
        price: "500",
        dh : true,
        nh: false,   
        dch:false,    
    },
    {
        id : 10,
        name : "Đồng hồ  2",
        img : "ĐH-2.jpg",
        price: "500",
        dh : true,
        nh: false,   
        dch:false,    
    },
    {
        id : 11,
        name : "Đồng hồ  3",
        img : "ĐH-3.jpg",
        price: "500",
        dh : true,
        nh: false,   
        dch:false,    
    },
    {
        id : 12,
        name : "Đồng hồ  4",
        img : "ĐH-4.jpg",
        price: "500",
        dh : true,
        nh: false,   
        dch:false,    
    },
    {
        id : 13,
        name : "Đồng hồ  5",
        img : "ĐH-5.jpg",
        price: "500",
        dh : true,
        best : true,
        nh: false,   
        dch:false,    
    },
    {
        id : 14,
        name : "Đồng hồ 6 ",
        img : "ĐH-6.jpg",
        price: "300",
        dh : true,
        best : true,
        nh: false,   
        dch:false,    
    },
    {
        id : 15,
        name : "Đồng hồ 7",
        img : "ĐH-7.jpg",
        price: "200",
        dh : true,
        best : true,
        nh: false,   
        dch:false,    
    },
    {
        id : 16,
        name : "Đồng hồ  8",
        img : "ĐH-8.jpg",
        price: "600",
        dh : true,
        best : true,
        nh: false,   
        dch:false,    
    },
    {
        id : 17,
        name : "Dây chuyền 1",
        img : "DC-1.jpg",
        price: "700",
        dh : false,
        best : true,
        nh: false,   
        dch:true,    
    },
    {
        id : 18,
        name : "Dây chuyền 2",
        img : "DC-2.jpg",
        price: "200",
        dh : false,
        best : true,
        nh: false,   
        dch:true,    
    },
    {
        id : 19,
        name : "Dây chuyền 3",
        img : "DC-3.jpg",
        price: "200",
        dh : false,
        best : true,
        nh: false,   
        dch:true,    
    },
    {
        id : 20,
        name : "Dây chuyền 4",
        img : "DC-4.jpg",
        price: "400",
        dh : false,
        best : true,
        nh: false,   
        dch:true,    
    },
    {
        id : 21,
        name : "Dây chuyền 5",
        img : "DC-5.jpg",
        price: "400",
        dh : false,
        nh: false,   
        dch:true,    
    },
    {
        id : 22,
        name : "Dây chuyền  6",
        img : "DC-6.jpg",
        price: "400",
        dh : false,
        nh: false,   
        dch:true,    
    },
    {
        id : 23,
        name : "Dây chuyền 7",
        img : "DC-7.jpg",
        price: "400",
        dh : false,
        nh: false,   
        dch:true,    
    },
    {
        id : 24,
        name : "Dây chuyền 8",
        img : "DC-8.jpg",
        price: "400",
        dh : false,
        nh: false,   
        dch:true,    
    },
    
   
]

