var data = [
    {
        id : 1,
        name : "Nước hoa 1",
        img : "NH-1.jpg",
        price: "200",
        best : true,
        NH : true,
        ĐH: false,
        DC: false,
        voucher:"",
    },
    {
        id : 2,
        name : "Nước hoa 2",
        img : "NH-2.jpg",
        price: "300",
        NH : true,
        best : true,
        DH: false,
        DC: false,
        voucher:"",
    },
    {
        id : 3,
        name : "Nước hoa 3",
        img : "NH-3.jpg",
        price: "400",
        NH : true,
        best : true,
        DH: false,
        DC: false,
        voucher:"" ,
    },
    {
        id : 4,
        name : "Nước hoa 4",
        img : "NH-4.jpg",
        price: "300",
        NH : true,
        best : true,
        DH: false,
        DC: false,
        voucher:"",
    },
    {
        id : 5,
        name : "Nước hoa 5",
        img : "NH-5.jpg",
        price: "300",
        NH : true,
        best : true,
        DH: false,
        DC: false,
        voucher:"",
    },
    {
        id : 6,
        name : "Nước hoa 6",
        img : "NH-6.jpg",
        price: "300",
        NH : true,
        best : true,
        DH: false,
        DC: false,
        voucher:"",
    },
    {
        id : 7,
        name : "Nước hoa 7",
        img : "NH-7.jpg",
        price: "300",
        NH : true,
        best : true,
        DH: false,
        DC: false,
        voucher:"",
    },
    {
        id : 8,
        name : "Nước hoa 8",
        img : "NH-8.jpg",
        price: "200",
        best : true,
        NH : true,
        DH: false,
        DC :false,
        voucher:"",
    },
    {
        id : 1,
        name : "Đồng hồ 1 ",
        img : "ĐH-1.jpg",
        price: "500",
        ĐH : true,
        best : true,
        NH: false,   
        DC:false,    
    },
    {
        id : 2,
        name : "Đồng hồ 2",
        img : "ĐH-2.jpg",
        price: "300",
        ĐH: true,
        best : true,
        DC: false,   
        NH:false,    
    },
    {
        id : 3,
        name : "Đồng hồ 2",
        img : "ĐH-3.jpg",
        price: "300",
        ĐH: true,
        best : true,
        DC: false,   
        NH:false,    
    },
    {
        id : 4,
        name : "Đồng hồ 2",
        img : "ĐH-4.jpg",
        price: "300",
        ĐH: true,
        best : true,
        DC: false,   
        NH:false,    
    },
    {
        id : 5,
        name : "Đồng hồ 2",
        img : "ĐH-5.jpg",
        price: "300",
        ĐH: true,
        best : true,
        DC: false,   
        NH:false,    
    },
    {
        id : 6,
        name : "Đồng hồ 2",
        img : "ĐH-6.jpg",
        price: "300",
        ĐH: true,
        best : true,
        DC: false,   
        NH:false,    
    },
    {
        id : 7,
        name : "Đồng hồ 7",
        img : "ĐH-7.jpg",
        price: "300",
        ĐH: true,
        best : true,
        DC: false,   
        NH:false,    
    },
    {
        id : 8,
        name : "Đồng hồ 8",
        img : "ĐH-8.jpg",
        price: "300",
        ĐH: true,
        best : true,
        DC: false,   
        NH:false,    
    },
    {
        id : 1,
        name : "Dây chuyền  1",
        img : "DC-1.jpg",
        price: "200",
        DH : false,
        best : true,
        NH: false,   
        DC:true,    
    },

    {
        id : 2,
        name : "Dây chuyền 2",
        img : "DC-2.jpg",
        price: "200",
        DH : false,
        best : true,
        NH: false,   
        DC:true,    
    },
    {
        id : 3,
        name : "Dây chuyền  3",
        img : "DC-3.jpg",
        price: "200",
        DH : false,
        best : true,
        NH: false,   
        DC:true,    
    },
    {
        id : 4,
        name : "Dây chuyền  4",
        img : "DC-4.jpg",
        price: "200",
        DH : false,
        best : true,
        NH: false,   
        DC:true,    
    },
    {
        id : 5,
        name : "Dây chuyền 5",
        img : "DC-5.jpg",
        price: "200",
        DH : false,
        best : true,
        NH: false,   
        DC:true,    
    },
    {
        id : 6,
        name : "Dây chuyền 6",
        img : "DC-6.jpg",
        price: "200",
        DH : false,
        best : true,
        NH: false,   
        DC:true,    
    },
    {
        id : 7,
        name : "Dây chuyền 7",
        img : "DC-7.jpg",
        price: "200",
        DH : false,
        best : true,
        NH: false,   
        DC:true,    
    },
    {
        id : 8,
        name : "Dây chuyền 8",
        img : "DC-8.jpg",
        price: "200",
        DH : false,
        best : true,
        NH: false,   
        DC:true,    
    },
   
]

