var data = [
    {
        id : 1,
        name : "Nước hoa nữ 1",
        img : "NH-1.jpg",
        price: "200",
        best : true,
        nh : true,
        watch: false,
        necklace: false,
        voucher:"",
    },
    {
        id : 2,
        name : "Nước hoa nữ 2",
        img : "NH-2.jpg",
        price: "300",
        nh : true,
        best : true,
        watch: false,
        necklace: false,
        voucher:"",
    },
    {
        id : 3,
        name : "Nước hoa nữ 3",
        img : "NH-3.jpg",
        price: "400",
        nh : true,
        best : true,
        watch: false,
        necklace: false,
        voucher:"" ,
    },
    {
        id : 4,
        name : "Nước hoa nữ 4",
        img : "NH-1.jpg",
        price: "200",
        nh : true,
        best : true,
        watch: false,
        necklace: false,
        voucher:"",
    },
    {
        id : 5,
        name : "Nước hoa nữ 5",
        img : "NH-1.jpg",
        price: "200",
        nh : true,
        watch: false,
        necklace: false,
        voucher:"",
    },
    {
        id : 6,
        name : "Nước hoa nữ 6",
        img : "NH-1.jpg",
        price: "200",
        nh : true,
        watch: false,
        necklace: false,
        voucher:"",
    },
    {
        id : 7,
        name : "Nước hoa nữ 7",
        img : "NH-1.jpg",
        price: "200",
        nh : true,
        watch: false,
        necklace: false,
        voucher:"",
    },
    {
        id : 8,
        name : "Nước hoa nữ 8",
        img : "NH-1.jpg",
        price: "200",
        nh : true,
        watch: false,
        necklace: false,
        voucher:"",
    },
    {
        id : 5,
        name : "Đồng hồ nữ 5",
        img : "ĐH-1.jpg",
        price: "500",
        watch : true,
        best : true,
        nh: false,   
        necklace:false,    
    },
    {
        id : 6,
        name : "Đồng hồ nữ 6",
        img : "ĐH-2.jpg",
        price: "300",
        watch : true,
        best : true,
        nh: false,   
        necklace:false,    
    },
    {
        id : 7,
        name : "Đồng hồ nữ 7",
        img : "ĐH-3.jpg",
        price: "200",
        watch : true,
        best : true,
        nh: false,   
        necklace:false,    
    },
    {
        id : 8,
        name : "Đồng hồ nữ 8",
        img : "ĐH-4.jpg",
        price: "600",
        watch : true,
        best : true,
        nh: false,   
        necklace:false,    
    },
    {
        id : 9,
        name : "Dây chuyền nữ 9",
        img : "DC-1.jpg",
        price: "700",
        watch : false,
        best : true,
        nh: false,   
        necklace:true,    
    },
    {
        id : 10,
        name : "Dây chuyền nữ 10",
        img : "DC-2.jpg",
        price: "200",
        watch : false,
        best : true,
        nh: false,   
        necklace:true,    
    },
    {
        id : 11,
        name : "Dây chuyền nữ 11",
        img : "DC-3.jpg",
        price: "200",
        watch : false,
        best : true,
        nh: false,   
        necklace:true,    
    },
    {
        id : 12,
        name : "Dây chuyền nữ 12",
        img : "DC-4.jpg",
        price: "400",
        watch : false,
        best : true,
        nh: false,   
        necklace:true,    
    },
   
]

